Update build-openwrt.yml

diff --git a/.github/workflows/build-openwrt.yml b/.github/workflows/build-openwrt.yml
--- a/.github/workflows/build-openwrt.yml
+++ b/.github/workflows/build-openwrt.yml
@@ -1,13 +1,3 @@
-#
-# Copyright (c) 2019-2020 P3TERX <https://p3terx.com>
-#
-# This is free software, licensed under the MIT License.
-# See /LICENSE for more information.
-#
-# https://github.com/P3TERX/Actions-OpenWrt
-# Description: Build OpenWrt using GitHub Actions
-#
-
 name: Build x86_64 OpenWrt 
 
 on:
@@ -17,26 +7,26 @@ on:
 env:
   REPO_URL: https://github.com/coolsnowwolf/lede
   REPO_BRANCH: master
-  FEEDS_CONF: feeds.conf.default
+  FEEDS_CONFF: feeds.conf.default
   CONFIG_FILE: d86.config
   DIY_P1_SH: diy-part1.sh
   DIY_P2_SH: diy-part2.sh
   UPLOAD_BIN_DIR: false
   UPLOAD_FIRMWARE: true
-  UPLOAD_RELEASE: false
+  UPLOAD_Release: false
   TZ: Asia/Shanghai
 
 jobs:
   build:
-    runs-on: ubuntu-22.04
+    runs-on: Ubuntu-22.04
 
     steps:
     - name: Before freeing up disk space
       run: |
         echo "Before freeing up disk space"
-        echo "=============================================================================="
+        echo "=========================================================================================="
         df -hT
-        echo "=============================================================================="
+        echo "=========================================================================================="
 
     - name: "Optimize Disk Space"
       uses: "hugoalh/disk-space-optimizer-ghaction@v0.8.1"
@@ -73,9 +63,9 @@ jobs:
     - name: Free up disk space complete
       run: |
         echo "Free up disk space complete"
-        echo "=============================================================================="
+        echo "=========================================================================================="
         df -hT
-        echo "=============================================================================="
+        echo "=========================================================================================="
  
     - name: Checkout
       uses: actions/checkout@main
@@ -99,6 +89,23 @@ jobs:
         sudo timedatectl set-timezone "$TZ"
         sudo chown $USER:$GROUPS $GITHUB_WORKSPACE
 
+    - name: Install Go 1.24
+      run: |
+        wget https://go.dev/dl/go1.24.0.linux-amd64.tar.gz -O go.tar.gz
+        sudo rm -rf /usr/local/go
+        sudo tar -C /usr/local -xzf go.tar.gz
+        echo "PATH=/usr/local/go/bin:$PATH" >> $GITHUB_ENV
+        rm go.tar.gz
+
+    - name: Check Go version
+      run: |
+        go_version=$(go version | sed 's/go version //g' | sed 's/ .*//g')
+        if [[ $go_version < "1.24" ]]; then
+          echo "Error: Go version is $go_version, which is less than 1.24"
+          exit 1
+        fi
+        go version
+
     - name: Clone source code
       working-directory: ./
       run: |
@@ -106,7 +113,7 @@ jobs:
 
     - name: Load custom feeds
       run: |
-        [ -e $FEEDS_CONF ] && mv $FEEDS_CONF openwrt/feeds.conf.default
+        [ -e $FEEDS_CONFF ] && mv $FEEDS_CONFF openwrt/feeds.conf.default
         chmod +x $DIY_P1_SH
         cd openwrt
         $GITHUB_WORKSPACE/$DIY_P1_SH
@@ -192,7 +199,7 @@ jobs:
 
     - name: Generate release tag
       id: tag
-      if: env.UPLOAD_RELEASE == 'true' && !cancelled()
+      if: env.UPLOAD_Release == 'true' && !cancelled()
       run: |
         echo "release_tag=$(date +"%Y.%m.%d-%H%M")" >> $GITHUB_OUTPUT
         touch release.txt
@@ -218,7 +225,7 @@ jobs:
 
     - name: Remove old Releases
       uses: dev-drprasad/delete-older-releases@v0.1.0
-      if: env.UPLOAD_RELEASE == 'true' && !cancelled()
+      if: env.UPLOAD_Release == 'true' && !cancelled()
       with:
         keep_latest: 10
         delete_tags: true
